from math import pi
import numpy as np

EARTH_RADIUS = 6.37E6
RADIUS_SCALING = 1E7
EARTH_RADIUS_SCALED = EARTH_RADIUS / RADIUS_SCALING
EARTH_MASS = 5.97E24
EARTH_SURFACE = 4 * pi * EARTH_RADIUS ** 2
EARTH_VOLUME = 4/3 * pi * EARTH_RADIUS ** 3
EARTH_VOLUME_SCALED = 4/3 * pi * EARTH_RADIUS_SCALED ** 3
EARTH_COLOR = (135, 206, 235)

MOON_RADIUS = 1.74E6
MOON_RADIUS_SCALED = MOON_RADIUS / RADIUS_SCALING
MOON_MASS = 7.34E22
MOON_SURFACE = 4 * pi * MOON_RADIUS ** 2
MOON_VOLUME = 4/3 * pi * MOON_RADIUS ** 3
MOON_VOLUME_SCALED = 4/3 * pi * MOON_RADIUS_SCALED ** 3
MOON_COLOR = (144, 144, 144)

SUN_RADIUS = 6.96E8
SUN_RADIUS_SCALED = SUN_RADIUS / RADIUS_SCALING
SUN_MASS = 2E30
SUN_SURFACE = 4 * pi * SUN_RADIUS ** 2
SUN_VOLUME = 4/3 * pi * SUN_RADIUS ** 3
SUN_VOLUME_SCALED = 4/3 * pi * SUN_RADIUS_SCALED ** 3
SUN_COLOR = (253, 184, 19)

SUN_EARTH_DISTANCE = 1.5E11
EARTH_MOON_DISTANCE = 3.84E8
SCALING_DISTANCE = 1E9
SUN_EARTH_DISTANCE_SCALED = SUN_EARTH_DISTANCE / SCALING_DISTANCE
EARTH_MOON_DISTANCE_SCALED = EARTH_MOON_DISTANCE / SCALING_DISTANCE

