from math import pi
import numpy as np

EARTH_RADIUS = 6.37E6
EARTH_RADIUS_SCALED = EARTH_RADIUS / EARTH_RADIUS
EARTH_MASS = 5.97E24
EARTH_SURFACE = 4 * pi * EARTH_RADIUS ** 2
EARTH_VOLUME = 4/3 * pi * EARTH_RADIUS ** 3
EARTH_VOLUME_SCALED = 4/3 * pi * EARTH_RADIUS_SCALED ** 3
EARTH_COLOR = np.array([135, 206, 235]) / 255

MOON_RADIUS = 1.74E6
MOON_RADIUS_SCALED = MOON_RADIUS / EARTH_RADIUS
MOON_MASS = 7.34E22
MOON_SURFACE = 4 * pi * MOON_RADIUS ** 2
MOON_VOLUME = 4/3 * pi * MOON_RADIUS ** 3
MOON_VOLUME_SCALED = 4/3 * pi * MOON_RADIUS_SCALED ** 3
MOON_COLOR = np.array([144, 144, 144]) / 255

